### ISSUE TITLE
Afficher les résultats pour tous les membres du foyer

### ISSUE THREAD

**Issue by guillett** [betagouv/aides-jeunes#1015]
L'AAH et l'ASS par exemple sont devenues des prestations individuelles. Pour le moment, Mes Aides n'affiche que les prestations calculées pour le demandeur ou la famille.

Il faudrait aussi afficher les prestations découvertes pour les autres membres du foyer. Cela permet de mieux comprendre les résultats des calculs.

Emails
- 04/01/2019 à 18:21 (PPA non affichée car AAH découverte)

**Comment by monbocal** [comment]
Je ne comprends pas "AAH prestation individuelle". Aux dernières nouvelles, et c'est un point sur lequel les associations se basent, les revenus du conjoint entrent en compte dans le calcul de l'AAH : https://informations.handicap.fr/a-AAH-revenus-conjoints-rejet-senat-11207.php .

**Comment by guillett** [comment]
Dans OpenFisca, l'AAH est rattaché à l'individu et non pas à la famille. C'est plus proche de la réalité « Une personne handicappée peut percevoir l'AAH ».

Les ressources de la famille sont bien prises en compte.
