### ISSUE TITLE
Supprimer le cumul ASS/AAH à partir de 2017

### ISSUE THREAD

**Issue by guillett** [betagouv/aides-jeunes#1017]
Ces prestations ne sont plus cumulables.

Code du travail - Article L5423-7

https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=7DB83B1E2CE13A4D14FCE21912F4C1C1.tplgfr43s_1?idArticle=LEGIARTI000033813814&cidTexte=LEGITEXT000006072050&dateTexte=20190107&categorieLien=id&oldAction=&nbResultRech=

Emails :
- 05/01/2019 à 11:10

**Comment by monbocal** [comment]
PR du 29 mai pour une implémentation naïve : https://github.com/betagouv/mes-aides-ui/pull/839

**Comment by guillett** [comment]
J'ai l'impression que la PR fait référence au cumul ASPA/AAH et pas ASS/AAH.
