### ISSUE TITLE
Annoncer plus tôt la non éligibilité aux aides calculées

### ISSUE THREAD

**Issue by monbocal** [betagouv/aides-jeunes#1038]
Il y a actuellement deux pages de "fin" de simulation :
- la première lorsque les ressources n-2 ne sont pas remplies, "Juste une dernière étape...", avec un CTA pour remplir les revenus n-2
- la seconde lorsque tout est rempli, "Vous n'êtes pas eligible...", avec un CTA vers d'autres solutions.

L'idée de base consiste à, plutôt que d'afficher un potentiel faux négatif, ne rien dire, puis ensuite afficher un vrai négatif. Ca se défend.

Mais à l'heure actuelle, je crois que ce faux négatif n'est un faux négatif que dans très peu de cas.
Le revenu n-2 intervient dans les aides nationales suivantes :
- Allocations familiales
- Complément familial
- PAJE de base
- AAH
- Allocation logement
- Bourse de collège
- Bourse de lycée
- Logement social

Détaillons cependant l'impact perçu dans les retours utilisateurs :
- les allocations familiales, le complément familial et la PAJE de base sont la plupart du temps déjà renseignés / le taux de recours est important sur ces aides, ce qui fait qu'il y a peu de chances qu'une famille avec deux enfants et un qui va naitre ne soit pas au courant qu'elle a droit aux allocations majorés et à la PAJE
- l'AAH dépend de la MDPH et notre but de simulation est de pouvoir simuler des changements de vie
- les bourses ont des fenêtres de demande très courtes, ce qui fait que 9 mois / 12, les signaler n'est pas utile
- le logement social est plus une information qu'une aide pécunière simple à demander
- l'allocation logement va changer de mode de calcul au printemps

--> Ma conclusion, c'est qu'avec le départ de l'allocation logement du revenu n-2, il n'y a plus de raison assez saillante pour garder ces 2 étapes de fin dans la simulation. Je propose de ne garder qu'une seule page de fin :
"Votre simulation ne vous a pas permis de découvrir de nouveaux droits",
avec un CTA qui change en fonction de la situation de la personne :
- en premier "Vous n'avez pas déclaré vos revenus n-2, cela peut faire apparaitre des droits que nous ne pouvons pas calculer actuellement"
- puis si tout est rempli, "D'autres solutions existent...".

(en lien avec #990)

**Comment by guillett** [comment]
Merci @monbocal pour ce récapitulatif. Pour moi, tant que les AL ne changent pas de période de référence, le CTA vers les revenus n-2 me parait pertinent.

Je te rejoins sur les prestations familiales pour lesquelles le non-recours est assez faible. Par contre pour le reste pas tout à fait. En particulier
- la simulation de changement de situation pour l'AAH doit se faire avec une base de comparaison fiable.
- l'affichage des bourses dès janvier me parait pertinent. Les demandes ne sont pas possibles aujourd'hui mais les utilisateurs seront au courant pour la prochaine période de demande.
- le logement social est effectivement différent mais beaucoup de gens ne sont pas au courant de leur éligibilité à ce dispositif.


Encore merci, la refonte de la page de résultats et plus globalement du parcours usager en fin de simulation est une opportunité pour encore mieux informer les usagers.

**Comment by monbocal** [comment]
Le but c'est surtout de se dire est ce qu'une fonctionnalité qui ne sert qu'une minorité parce qu'on veut à tout prix éviter un faux négatif n’entraîne pas plus de messages au support ? Pour moi la réponse est oui. On a une page qui sert à éviter une minorité de faux négatifs pour une minorité d'utilisateurs...

**Comment by guillett** [comment]
Pourrais-tu ajouter une section Email au commentaire initial de l'issue avec des références vers les emails reçus en lien avec l'issue ?

Effectivement, tu as raison aujourd'hui pour avoir « Juste une dernière étape » il faut avoir beaucoup de ressources (car non éligible au logement social [dont les critères de ressources sont très larges]).

Il faudrait voir si on peut savoir rapidement combien de personnes cela représente.
