### ISSUE TITLE
Ne pas systématiquement supposer qu'un demandeur d’emploi est sans activité

### ISSUE THREAD

**Issue by MattiSG** [betagouv/aides-jeunes#107]
En tant que bénéficiaire potentiel demandeur d’emploi travaillant actuellement,
Je peux signifier que j’ai déjà un contrat de travail,
Pour ne pas être contraint de donner une date de fin de dernier contrat
- [ ] Déterminer l’éligibilité à l’ASS.

**Comment by guillett** [comment]
Il s'agit du dernier contrat de travail précédant le premier versement d'ARE :

> Vous devez avoir travaillé au moins 5 ans (à temps plein ou à temps partiel) au cours des 10 ans avant la fin de votre contrat de travail qui précédait le versement de l'ARE.

https://www.service-public.fr/particuliers/vosdroits/F12484

**Comment by monbocal** [comment]
+1 10/03/17 20:47 : professionnel secteur social
+1 11/03/17 21:37 : intermittent du spectacle
(pardon pour l'issue duplicate)
