### ISSUE TITLE
Aide de 500€ pour apprentis pour le permis depuis 01/01/2019

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/aides-jeunes#1093]
https://demarchesadministratives.fr/actualites/500-daide-pour-les-apprentis-pour-passer-le-permis-de-conduire-depuis-le-1er-janvier-2019

**Comment by guillett** [comment]
Merci beaucop @jbledevehat pour cette suggestion. J'y vois une opportunité pour Mes Aides et Démarches simplifiées pour offrir un service de qualité. J'ajoute @Benjamin-Doberset
