### ISSUE TITLE
Gestion des changements de situation (plus au moins majeurs)

### ISSUE THREAD

**Issue by monbocal** [betagouv/aides-jeunes#1159]
Lors d'un incident majeur de vie, beaucoup de personnes utilisent le simulateur - mais ne savent pas comment le remplir, il n'existe aucun parcours fléché pour un décès, un divorce ou un handicap par exemple.

Une meilleure intégration a été demandée lors de l'Open Lab en Seine et Marne.

**Comment by guillett** [comment]
La question se pose aussi pour des changements de situations moins majeurs comme la reprise d'un emploi.

Email de la DIRECCTE le 17/06/2019 à 10:11
