### ISSUE TITLE
Prendre en compte le chômage partiel

### ISSUE THREAD

**Issue by MattiSG** [betagouv/aides-jeunes#120]
En tant que bénéficiaire potentiel travaillant moins de 77h/mois,
Je peux bénéficier de règles de calcul spécifiques,
Pour avoir une estimation correcte de mon éligibilité aux différentes prestations

**Comment by HelaG** [comment]
Pour les AL :

Un abbatement de 30% est appliqué aux ressources n-2 en cas d'activité partielle du demandeur > à 40h de travail sur les 2 derniers mois. 
Afin d'appliquer correctement cette règle il faudrait que quand un utilisateur déclare des indemnité d'activté partielle, on lui demande s'il a travaillé au moins 40h au cours des 2 derniers mois. Si oui alors on applique un abattement de 30% sur les revenus n-2. 

L'abattement s'applique également si le conjoint du demandeur est en chômage partiel.

**Comment by HelaG** [comment]
@AnneLaure-M Est-ce que la situation de chômage partiel a un impact sur les autres presta?

**Comment by guillett** [comment]
Pour les 40h des aides au logement [ Code de la construction et de l'habitation - Article R351-13 ] (https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=1975166C77B026920406BCFCDD9C615A.tplgfr27s_3?cidTexte=LEGITEXT000006074096&idArticle=LEGIARTI000021632302&dateTexte=20190204&categorieLien=cid#LEGIARTI000021632302)

Pour la PAJE [ Code de la sécurité sociale - Article R532-7 ] (https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000031694522&cidTexte=LEGITEXT000006073189).
