### ISSUE TITLE
À la fin du questionnaire, confirmer ou non que nous percevons les aides listées

### ISSUE THREAD

**Issue by numahell** [betagouv/aides-jeunes#1219]
À la fin du questionnaire, on pourrait confirmer (ou non) que nous percevons bien les aides listées, et le cas échéant indiquer quelles aides nous ne percevons pas.

**Comment by guillett** [comment]
Bonjour @numahell et désolé pour le délai de réponse.

Nous avons amélioré la page de résultats en début d'année et cherchons toujours à améliorer la pertinence des informations affichées (avec #1162 par exemple).

Il n'y a pas beaucoup de place sur cette page de résultats et tellement de choses à afficher.

On pourra poser les questions suivantes, progressivement en fonction des réponses.
Pour chaque prestation, un lien/question :
- Le saviez-vous déjà ?
  - Oui. Bénéficiez-vous de cette prestation ?
    - Oui. Si c'est un montant, le montant indiqué est-il correct ?
      - Oui. _Ouf_ **FIN**
      - Non. Aie, aidez-nous svp :) **FIN**
    - Non. Mais pourquoi ?
      - Je n'y suis en réalité pas éligible.
        - Aidez-nous à améliorer le moteur de calculs svp. **FIN**
      - Je me suis perdu dans les démarches
        - Dites nous ce qui s'est passé pour qu'on essaie de faire aboutir votre demande. **FIN**
      - Je ne sais plus
        - Vous ré-essayez et nous dites si vous êtes bloqué pour qu'on vous accompagne. **FIN**
  - Non. _Cool_ on a lutté contre le problème de non-information du non-recours aux prestations sociales. **FIN**

**Comment by guillett** [comment]
Le suivi analytique des réponses à ces questions sera très intéressant pour évaluer la pertinence du choix de prise en compte des impacts inter-prestations des prestations découvertes mais non déclarées par les usagers.

C'est particulièrement important pour le FSL 22 car les droits potentiels (ou non déclarés) cachent trop souvent l'éligibilité à ce dispositif.

**Comment by guillett** [comment]
Un échange d'idée pour le texte du lien, quelques verbes, mots qui nous sont passés par la tête.
- Fiabiliser
- Compléter
- Améliorer
- Comparer avec votre situation
- Affiner
- Confirmer
- Décalage
- Correspondance
- Je ne comprends pas
- Votre réalité actuelle
