### ISSUE TITLE
Améliorer le sélecteur de nationalité

### ISSUE THREAD

**Issue by alexsegura** [betagouv/aides-jeunes#1277]
Dans le sélecteur de nationalité, on devrait pouvoir taper soit la nationalité (avec ses variantes, par exemple Grecque/Héllénique), soit le nom du pays.

**Comment by guillett** [comment]
Dans la version VueJs, le selecteur de nationalité a été simplifié (car les résultats de la version complexe n'étant pas significativement meilleurs).

cf.
    "world-countries": "github:alexsegura/countries#translate-demonyms"
