### ISSUE TITLE
Actualiser les barèmes des bourses du collège et du lycée

### ISSUE THREAD

**Issue by guillett** [betagouv/aides-jeunes#1413]
Email
- 04/11/2019 à 14:52

**Comment by sandcha** [comment]
Voici ce que je comprends de la mise à jour nécessaire : 

**Bourse collège**

Dans les paramètres openfisca-france, il nous faut mettre à jour [ces YAML bourse_college](https://github.com/openfisca/openfisca-france/tree/master/openfisca_france/parameters/bourses_education/bourse_college) afin qu'ils reflètent, par échelon de revenus et nombre d'enfant, les dernières valeurs de plafonds et le montant de la bourse.

Sachant que :
* Les dernières valeurs sont disponibles sur [cette page education.gouv.fr](https://www.education.gouv.fr/cid88/les-aides-financieres-au-college.html#Les%20bourses%20de%20collège) (paragraphe `Montant des bourses et plafonds de ressources`),
* Les valeurs sont publiées par [circulaire](https://www.education.gouv.fr/pid285/bulletin_officiel.html?cid_bo=132506) (source : [service-public.fr](https://www.service-public.fr/particuliers/vosdroits/F984)) et ce sont les montants trimestriels qui y sont exprimés (3 versements par année scolaire,
* Dans openfisca-france, le montant **mensuel** de la bourse n'est pas exprimé en € mais en % de la [BMAF à la même date](https://fr.openfisca.org/legislation/prestations.prestations_familiales.af.bmaf).

**Bourse lycée**

Dans les paramètres openfisca-france, il nous faut mettre à jour [ces YAML bourse_lycee](https://github.com/openfisca/openfisca-france/tree/master/openfisca_france/parameters/bourses_education/bourse_lycee) afin qu'ils reflètent, par échelon de revenus et nombre d'enfant, les dernières valeurs de plafonds et le montant de la bourse.

Sachant que : 
* Les dernières valeurs sont disponibles sur [cette page education.gouv.fr](https://www.education.gouv.fr/cid151/aides-financieres-au-lycee.html) (qui référence [ce barème](https://cache.media.education.gouv.fr/file/03_-_mars/58/0/Bareme_bourses_nationales_lycee_2019-2020_1094580.pdf))
* Les valeurs sont publiées par [circulaire](https://www.education.gouv.fr/pid285/bulletin_officiel.html?cid_bo=129659) (source : [service-public.fr](https://www.service-public.fr/particuliers/vosdroits/F616) et ce sont les montants trimestriels qui y sont exprimés (3 versements par année scolaire),
* Dans openfisca-france, le montant **mensuel** de la bourse n'est pas exprimé en € mais en % de la [BMAF à la même date](https://fr.openfisca.org/legislation/prestations.prestations_familiales.af.bmaf).

@guillett Est-ce bien cela ? 🙂

**Comment by sandcha** [comment]
De plus, la formule de calcul restant inchangée pour [bourse_college](https://fr.openfisca.org/legislation/bourse_college) et [bourse_lycee](https://fr.openfisca.org/legislation/bourse_lycee), nous n'avons pas besoin d'ajouter de fichier YAML : il nous faut ajouter des lignes pour 2019 (ou 2018 toujours valable en 2019 selon la date d'application de la dernière circulaire) dans le répertoire `apres_2016` correspondant pour le [college](https://github.com/openfisca/openfisca-france/tree/master/openfisca_france/parameters/bourses_education/bourse_college/apres_2016) et le [lycée](https://github.com/openfisca/openfisca-france/tree/master/openfisca_france/parameters/bourses_education/bourse_lycee/apres_2016), n'est-ce pas ?
