### ISSUE TITLE
RSA étudiant

### ISSUE THREAD

**Issue by louisremi** [betagouv/aides-jeunes#154]
En matière de RSA, la règle veut qu'il ne soit pas accessible aux étudiants. Le site vosdroits.service-public.fr indique néanmoins [plusieurs exceptions](http://vosdroits.service-public.fr/particuliers/F1971.xhtml) à cette règle, qui ne semblent pas être prises en compte par le simulateur.

(Personellement je suis (auto-)entrepreneur depuis plusieurs années et ai postulé cette année au statut d'étudiant-entrepreneur, ce qui me permettrait de bénéficier d'accompagnement et de locaux.)

**Comment by HelaG** [comment]
@louisremi merci de ta contribution!
Effectivement des étudiants de percevoir du RSA, à notre connaissance ces règles sont principalement liées à l'âge du demandeur. 

L'idéal (si on peut abuser de ton temps) serait que tu rentres un test à partir de ta simulation. Pour ça il suffit de cliquer là-dessus en fin de simulation :
![contrib](https://cloud.githubusercontent.com/assets/12069445/9763794/b92be0aa-570b-11e5-8b9b-12e659bce231.png)




Est-ce que tu as rentré des ressources dans ta simulation ? 
En fait, l'idéal pour qu'on puisse mieux comprendre le cas

**Comment by HelaG** [comment]
Ton mot de passe c'est: sgmap2014 :)

**Comment by louisremi** [comment]
J'ai créé le test : https://mes-aides.gouv.fr/tests/55f040bf0d70943004ddce60/show
Dites moi si ça vous convient

**Comment by HelaG** [comment]
Super merci! On va regarder ça!

Et je supprime le comment avec ton mdp...

**Comment by monbocal** [comment]
Je remonte cette issue avec le feedback reçu le 02/02/17 10:23.

**Comment by MattiSG** [comment]
> feedback reçu le 02/02/17 10:23

Je ne suis pas sûr que ce soit la même chose : cette _issue_ est à propos d'une personne qui a une exception à la non-éligibilité (i.e. le simulateur lui dit 0€ mais il est dans un cas spécifique où il est éligible), alors que le feedback du 02/02/17 est une personne qui a une exception à l'éligibilité (i.e. le simulateur lui dit 540€ mais il est dans un cas où il n'est pas éligible car étudiant, même si plus de 26 ans).
@fpagnoux tu confirmes mon interprétation ?

**Comment by fpagnoux** [comment]
Je confirme.

**Comment by fpagnoux** [comment]
https://github.com/sgmap/mes-aides-ui/issues/452
