### ISSUE TITLE
Code postal de la commune des parents

### ISSUE THREAD

**Issue by restuccia** [betagouv/aides-jeunes#1619]
Hello,

J'espère que c'est le bon repo pour cette issue :)

Le simulateur sur https://mes-aides.1jeune1solution.beta.gouv.fr/ demande le code postal de la commune des parents, et le champ est obligatoire. Mais l'utilisateur n'a aucun moyen de indiquer si les parents ne vivent pas en France.

Merci !

![Capture d’écran 2021-04-28 à 13 04 29](https://user-images.githubusercontent.com/51122275/116394366-1edc2e00-a823-11eb-91dd-d6be9acd5728.jpg)

**Comment by guillett** [comment]
C'est carrément le bon endroit et désolé pour le retour qui traîne. On a été un peu sous l'eau avec le lancement.

On a corrigé le problème que tu as signalé [2 jours après ton signalement](https://github.com/betagouv/aides-jeunes/pull/1621#event-4666916725). Les jeunes dont les parents vivent à l'étranger ne sont plus bloqués !

Merci beaucoup pour ton message !

**Comment by restuccia** [comment]
Merci à toi et à toute l'équipe pour le super boulot ! :)
