### ISSUE TITLE
Prendre en compte les réfugiés

### ISSUE THREAD

**Issue by MattiSG** [betagouv/aides-jeunes#162]
En tant que bénéficiaire potentiel réfugié,
Je peux décrire mon statut de réfugié,
Pour évaluer mes droits

**Comment by fpagnoux** [comment]
Métronews travaille pour nous: 
http://www.metronews.fr/conso/migrants-a-quelles-allocations-ont-ils-vraiment-droit/moik!nwfBTLIpMMrM/
