### ISSUE TITLE
Améliorer la capture des revenus n-2

### ISSUE THREAD

**Issue by MattiSG** [betagouv/aides-jeunes#167]
Retour test utilisateur UDAF92 :
- [ ] Bouton retour / annuler.
- [x] Ajouter la mention « Pour information » à la précision du montant sur les 12 derniers mois.
- [ ] Rendre lisible le fait qu'aucun champ n'est obligatoire.

**Comment by guillett** [comment]
Si les champs contiennent leur valeur par défaut, j'ai le sentiment que ça règle le manque de bouton retour/annuler et le caractère facultatif des champs est renforcé.

Cela fait peut paraître redondant avec le contenu "Pour information ..." mais il s'agit bien de deux informations différentes.

![capture d ecran 2017-02-02 a 12 37 34](https://cloud.githubusercontent.com/assets/1410356/22547936/692da7ec-e944-11e6-9eb4-88fd7260d429.png)

Techniquement, il devrait être possible de modifier ```zero-to-empty``` en ```empty-to-default``` et ajouté un attribut ```default``` (si != 0)

Qu'en pensez-vous ?

**Comment by MattiSG** [comment]
Non, tout préremplissage fait craindre aux utilisateurs de modifier la valeur. Beaucoup supposent qu'on est l'administration et qu'on sait mieux qu'eux, car ça rappelle le préremplissage de la feuille d'impôts (surtout pour cet écran !).
