### ISSUE TITLE
Prendre en compte les pensions alimentaires annuelles dans l'éligibilité à l'ASF

### ISSUE THREAD

**Issue by HelaG** [betagouv/aides-jeunes#182]
En tant que bénéficiaire potentiel déclarant un montant annuel de pensions alimentaires,
Je peux une évaluation exacte de mon droit à l'ASF.

**Comment by HelaG** [comment]
(https://mes-aides.gouv.fr/tests/55f022fa0d70943004ddcca2/show?keyword=recette&state=pending&state=validated)[cf test recette Caf 44]

**Comment by guillett** [comment]
Il serait intéressant – si la personne déclare ne pas percevoir la totalité de la pension alimentaire qui lui est due - de créer un lien non seulement sur la page caf.fr - ASF mais aussi sur https://www.pension-alimentaire.caf.fr.

En plus, on pourrait ajouter l'éligibilité à l'aide de la CAF ou de la MSA pour la récupération de la part de la pension alimentaire manquante.

cf. https://www.pension-alimentaire.caf.fr/ma-pension-alimentaire-n-est-pas-payee
