### ISSUE TITLE
Problème d'association des codes postaux

### ISSUE THREAD

**Issue by mquandalle** [betagouv/aides-jeunes#2379]
Par exemple taper `78600`, la ville Saint-Germain-en-Laye ne devrait pas sortir :

![image](https://user-images.githubusercontent.com/1730702/151178419-4c90d4ea-e6e1-485f-987e-188bcbff176d.png)

Potentiellement lié à https://github.com/etalab/decoupage-administratif/issues/25 (en gros le code postal d'une commune limitrophe est parfois inclus dans la base de donnée Etalab).

**Comment by ThomasG77** [comment]
A fermer. cf https://github.com/etalab/decoupage-administratif/issues/25
Pour le cas mentionné, https://geo.api.gouv.fr/communes?codePostal=78600 ne retourne plus que Maisons-Laffitte et Le Mesnil-le-Roi maintenant comme on est aligné avec La Poste (cf https://datanova.laposte.fr/explore/dataset/laposte_hexasmal/table/?disjunctive.code_commune_insee&disjunctive.nom_de_la_commune&disjunctive.code_postal&disjunctive.ligne_5&refine.code_postal=78600 pour comparaison)

**Comment by mquandalle** [comment]
Je viens de tester le problème est encore présent sur aides-jeune, je ne sais pas exactement quelle API est utilisée.

**Comment by ThomasG77** [comment]
C'est une API soit dérivée de l'API Découpage Administrative ou de ses données, soit sans rapport car en regardant l'URL d'appel, c'est https://mes-aides.1jeune1solution.beta.gouv.fr/api/outils/communes/78600
Le retour JSON contient plus de clés que l'API Découpage Administratif existante

**Comment by Cugniere** [comment]
Corrigé dans PR #2433
