### ISSUE TITLE
MAJ aides vélo

### ISSUE THREAD

**Issue by mquandalle** [betagouv/aides-jeunes#2429]
Il y a eu pas mal de mises à jour depuis le début d'année sur les aides vélo, des nouvelles villes se sont lancés : Brest, Saint-Étienne, Saint Brieuc, etc. et quelques unes se sont arrêtés.

Liste des changements sur https://github.com/mquandalle/mesaidesvelo/blob/master/package-aides-velo/CHANGELOG.md

Pour info je réfléchis à rapatrier l'association d'image sur mon dépôt afin de synchroniser l'ajout d'une aide et celle de son image.

**Comment by Cugniere** [comment]
Mise à jour dans la PR #2452
