### ISSUE TITLE
Ajouter les aides veuvage

### ISSUE THREAD

**Issue by MattiSG** [betagouv/aides-jeunes#282]
Source : mail du
- 04/05/2016 à 13h27
- 13 Jun 2017
- 23/01/2020 à 15:22

**Comment by monbocal** [comment]
Up, à la fois comme nouvelle aide et comme ressource à déclarer sur la page Ressources !

**Comment by guillett** [comment]
@monbocal 

Aurais-tu plus d'informations ?

- Références OpenFisca/Légifrance (Eligibilité, Montant, etc.)
- Identifier la catégorie correspondante pour l'estimation des revenus A-1 (cf. https://github.com/sgmap/mes-aides-ui/blob/master/app/js/constants/ressources.js#L322)

**Comment by monbocal** [comment]
L'allocation veuvage c'est ça : https://www.service-public.fr/particuliers/vosdroits/F744 . C'est réservé aux moins de 55 ans, après on part sur le principe de la pension de réversion.

Pour sa catégorie, http://bofip.impots.gouv.fr/bofip/317-PGP me dit que c'est une pension et rente viagère imposable, d'où la catégorie "Retraite imposable" ?

> L'allocation de veuvage servie en application de ces dispositions par la caisse nationale d'assurance-vieillesse des travailleurs salariés constitue un revenu imposable dans la catégorie des pensions

**Comment by monbocal** [comment]
Hello, up, on vient de m'en parler à nouveau par mail aujourd'hui :)

**Comment by guillett** [comment]
Retour médiateur par email le 10/07/17 à 14:42 :

> J'en profite pour faire remonter une nouvelle proposition concernant les personnes mariées qui sont veuves et qui pourraient avoir droit soit à l'allocation veuvage ou à la pension de réversion selon leur âge et en fonction de la date du décés du conjoint.
> Vous notez dans votre simulateur: votre situation "Isolé " ou "couple" mais si la personne  coche "isolée" il faudrait qu'elle puisse préciser ensuite si elle est veuve ou non et que si elle coche "oui" que le simulateur puisse vérifier si elle est éligible à l'allocation veuvage ou à la pension de réversion.
