### ISSUE TITLE
Une fois par semaine une action GitHub poste un message contenant les liens cassés.

### ISSUE THREAD

**Issue by Kout95** [betagouv/aides-jeunes#2945]

**Comment by guillett** [comment]
TEST

|Aide|Info|✎|
|-|-|-|
|caf-nord-aide-achat-equipement<br/>https://caf.fr/sites/default/files/caf/598/IMPRIMES/DEQUIP_2021.pdf|404<br/>765|✎|
|caf-nord-aide-achat-equipement<br/>https://caf.fr/allocataires/caf-du-nord/offre-de-service/logement-et-cadre-de-vie/une-aide-pour-l-achat-d-un-ordinateur|404<br/>765|✎|
|caf-alpes-maritimes-aide-autonomie-jeunes<br/>https://www.caf.fr/allocataires/caf-des-alpes-maritimes/offre-de-service/enfance-et-jeunesse/l-aide-a-l-autonomie-des-jeunes-aaj|404<br/>151|✎|
|caf-alpes-maritimes-aide-autonomie-jeunes<br/>https://www.caf.fr/sites/default/files/caf/061/Documents/OFFRESCE/ENFANCEJEUNESSE/2021/NOTICE%20-%20DEMANDE%20AAJ%20%20sept%2021%20juin%2022%20%28MAJ%2005%2010%2021%29.pdf|404<br/>151|✎|
|caf-alpes-maritimes-aide-autonomie-jeunes<br/>https://www.caf.fr/sites/default/files/caf/061/Documents/OFFRESCE/ENFANCEJEUNESSE/2020/Demande_2020_aide_autonomie_jeunes.pdf|404<br/>151|✎|

**Comment by guillett** [comment]
test

**Comment by guillett** [comment]
Le suivi des liens cassés est désormais fait via Grist et non plus avec cette issue. Je la ferme (l'issue).
