### ISSUE TITLE
ACTP et Complément de ressources AAH : dénominations, calculs ?

### ISSUE THREAD

**Issue by fpagnoux** [betagouv/aides-jeunes#365]
En tant que bénéficiaire de l'ACTP (ancienne PCH)
Je peux la déclarer sur mes-aides,
pour qu'elles soit prise en compte dans le calcul de mes prestations

**Comment by monbocal** [comment]
+1 mail 10/03/17 10:52

**Comment by monbocal** [comment]
Up !

"Bonjour,dans le menu déroulant "allocations" je me suis heurté à 2 problèmes:
1/Complément AAH est le nom d'une allocation du temps de la COTOREP,réformée en 2005.L'intitulé exact,pour éviter toute confusion des demandeurs,est:Complément de ressources AAH.Il serait utile de modifier l'énnoncé dans le menu déroulant.
2/Seule la PCH est proposée.Or,même si elle n'existe plus depuis 2005 pour les demandeurs,certaines personnes,comme moi,perçoivent encore l'ACTP(option réservée à ceux qui percevaient déjà cette allocation avant la loi de 2005).Il serait utile de rajouter cette allocation dans les menus déroulants."
