### ISSUE TITLE
Indiquer la durée d'attribution

### ISSUE THREAD

**Issue by MattiSG** [betagouv/aides-jeunes#386]
Indiquer que le RSA peut être fourni en l'attente de l'attribution de l'AAH, avec subrogation (remboursement du reliquat au département).

**Comment by monbocal** [comment]
Je faisais une recherche sur les issues et suis tombé sur celle là. Est ce que cette issue peut être réglée en modifiant droits.js pour le RSA, ou bien est ce que ce serait ajouter trop d'importance à une exception ?

**Comment by MattiSG** [comment]
Dans le RSA, ce serait trop important, mais dans la description de l'AAH ça me semble acceptable  🙂

**Comment by monbocal** [comment]
J'ai du mal à trouver un texte officiel pour baser la formulation : d'où tiens tu cette information ?

**Comment by MattiSG** [comment]
Source interne DGCS  😞
Je ne pense pas que ça soit défini quelque part explicitement : l'AAH mettant plusieurs mois à être liquidée à cause des délais de traitement en MDPH, le RSA est de droit.
