### ISSUE TITLE
Déclarer des revenus en tant qu'artiste

### ISSUE THREAD

**Issue by MattiSG** [betagouv/aides-jeunes#433]
En tant que bénéficiaire potentiel relevant du régime des artistes,
Je peux déclarer mes revenus,
Pour évaluer mes droits.

- - - -

Source : mail du 11 janvier 2017 à 19:16:10.
+1 Sylvain : mail du 06/03/17 20:14 et suivants (précisions)

- - - -

Également concernés (cf. #22) :

- Piges.
- Droits d'auteur.
- Cachets.

**Comment by MattiSG** [comment]
A priori, pour le RSA (via @fpagnoux) :

> Pour les artistes auteurs dont les revenus sont constitués du montant brut des droits d’auteurs (assimilés fiscalement à des traitements et salaires) :
> Prise en compte des salaires nets perçus avant saisies retenues (à déclarer comme des revenus d’activité)
> Pour les artistes auteurs qui ont des revenus non salariés (BNC) :
> En cas d’imposition au régime forfaitaire : Prise en compte du montant des BNC déclarés mensuellement ou trimestriellement, déduction faite d’un abattement forfaitaire fiscal de 34 %
> En cas d’imposition au régime réel ou début d’activité : évaluation des revenus par le PCD.

> Le PCD apparemment, d’après la DGCS et DSS, ce n’est pas du tout systématique. C’est plutôt un droit discrétionnaire de modification de ta base ressource, qui peut être favorable (à ta demande en général) ou défavorable.

**Comment by MattiSG** [comment]
Recherche spontanée d'un utilisateur :

> je cherchais la case "artiste auteur" dans revenus professionnels non-salariés pour déclarer des ventes de dessins faites à des particuliers, sans TVA.

**Comment by monbocal** [comment]
+1

**Comment by monbocal** [comment]
+1 mail 16/03/17 11:28
