### ISSUE TITLE
Corriger accès moncomptepro sur la prod (en attente)

### ISSUE THREAD

**Issue by Shamzic** [betagouv/aides-jeunes#4400]
Prérequis: https://trello.com/c/DvsIayGG/1710-faire-la-demande-datapass-pour-autoriser-les-id-moncomptepro-sur-lenvironnement-production

### 25/06 

Julie a échangé avec Edouard. Pas de blocage sur le principe. En attente d'un retour avec la liste des points RGPD dû aux futurs accès des données par des personnes externes.
Début de solution technique entamé.
To do : formalité de demande d'habilitation pour passer en prod sur mon compte pro

**Comment by jenovateurs** [comment]
Contexte TZNR, voir pour transférer le besoin à l'équipe Aides simplifiées.
