### ISSUE TITLE
offboarding de Sami

### ISSUE THREAD

**Issue by jenovateurs** [betagouv/aides-jeunes#4407]
suivre l’outil d’offboarding pour supprimer les accès

Chatwoot : yasmine ✅ 
Sentry : jérémy
OF: simon ✅

**Comment by Shamzic** [comment]
L'adresse de Sami n'est pas présente dans la team aides-jeunes sur Sentry : https://sentry.incubateur.net/settings/betagouv/teams/aides-jeunes/members/

Je met ce ticket en statut terminé
