### ISSUE TITLE
Ajouter l'école primaire sur la question de la scolarité

### ISSUE THREAD

**Issue by jenovateurs** [betagouv/aides-jeunes#4424]
![Image](https://github.com/betagouv/aides-jeunes/assets/18016058/ac655166-999d-41e2-ab7e-1d26b473d398)

- [ ] Ajouter A l'école primaire pour la question "où êtes-vous scolarisé"
- [ ] Abaisser l'age minimum à 4 ans pour afficher la question où êtes-vous scolarisé - minimum pour accéder à l'ARS
- [ ] Ajouter l'option dans le fichier block si la case école primaire a été coché
- [ ] Faire des tests :-).

**Comment by Julie-Mrshl** [comment]
Prio du 11/07 : 
Ajouter le choix "Ecole primaire" à la question "où sera scolarisé l'enfant à la rentrée ?"
Ne pas l'ajouter sur la question "où êtes-vous scolarisé(e) ?"
