### ISSUE TITLE
Montrer le Pass Sport aux bénéficiaires de l'allocation de rentrée scolaire

### ISSUE THREAD

**Issue by jenovateurs** [betagouv/aides-jeunes#4425]
- NB : l'ARS est ouverte aux personnes inscrites à l'école, au collège ou au lycée (voir dates sur la page du pass sport : https://www.pass.sports.gouv.fr/v2/tout-savoir-sur-le-pass-sport#pour-qui)

Pour afficher ce dispositif : 
- Besoin d'ajouter l'école primaire  (#4424)
- Afficher l'ARS dans les résultats pour les écoliers, les collégiens et les lycéens
- Vérifier que le lien avec l'ARS et le Pass Sport fonctionne

**Comment by Shamzic** [comment]
Pour moi ça me semble OK depuis la dernière mise en production concernant l'ARS. 

J'arrive à obtenir une allocation de rentrée scolaire + pass sport dans la même simulation pour une personne avant un enfant, mais c'est parce que le pass sport est pour le demandeur et l'allocation de rentrée pour l'enfant. 

Est-ce qu'on voudrait afficher le pass sport aussi dans le cas où les enfants du demandeur y sont éligibles ? Actuellement ce n'est pas le cas et il faudrait probablement modifier la modélisation openfisca

**Comment by Shamzic** [comment]
Vue à l'oral : Todo => màj modélisation openfisca pour tester l'éligibilité à tous les membres de la famille
