### ISSUE TITLE
Montrer le Pass Sport aux enfants bénéficiaires de l'AEEH

### ISSUE THREAD

**Issue by Julie-Mrshl** [betagouv/aides-jeunes#4462]
- [ ] Réparer le simulateur pour afficher l'AEEH / surement un soucis avec aeeh_niveau_handicap qu'il faudrait calculer ou mettre une valeur par défaut / https://github.com/betagouv/aides-jeunes/issues/4499
- [ ] Vérifier que le pass sport s'affiche bien

**Comment by jenovateurs** [comment]
Me semble ok.

![Image](https://github.com/user-attachments/assets/6d3ce49d-018e-47d3-b6ac-78f0df5b0c6c)
