### ISSUE TITLE
Erreur de gestion de cache sur les enfants a charge

### ISSUE THREAD

**Issue by jenovateurs** [betagouv/aides-jeunes#4497]
https://github.com/user-attachments/assets/199a894a-c537-4055-a223-b00bc2ecb2f1

**Comment by jenovateurs** [comment]
Soucis de classement des enfants et surtout du cache dans les paramètres, résultat on arrive pas à supprimer la classe.

**Comment by yasmine-glitch** [comment]
lié à la discussion suivante : https://mattermost.incubateur.net/betagouv/pl/cj1rt5wcxfyyukf73617rkjiqo
