### ISSUE TITLE
FAQ : mettre le lien de la FAQ sur la page d'accueil, dans les pages "En savoir plus"

### ISSUE THREAD

**Issue by yasmine-glitch** [betagouv/aides-jeunes#4567]
FAQ : toutes nos réponses à vos questions les plus fréquentes (notamment "Comment faire une demande de Complémentaire Santé Solidaire (ex-CMU))

**Comment by Shamzic** [comment]
Je modifie le titre en retirant "et le footer" car c'est déjà présent dans le footer
