### ISSUE TITLE
Investivagation OF Paris

### ISSUE THREAD

**Issue by jenovateurs** [betagouv/aides-jeunes#4574]
- [x] S'assurer que les aides présentes dans OF Paris sont toujours à jour
- [x] Vérifier si les aides OF Paris sont affichés dans le simulateur avec les stats Matomo
- [x] Comprendre comment la liaison OF Paris et AJ devrait fonctionner ou la réparer

**Comment by jenovateurs** [comment]
Note Complémentaire : 
- Dernière MAJ d'OF Paris - Il y a ~3 ans : https://github.com/openfisca/openfisca-paris 
- Jan 11, 2022 - pour les aides
- Aug 26, 2021 - pour les tests

**Comment by jenovateurs** [comment]
Liste des potentielles aides d'OF Paris : 
- Allocation de soutien aux parents d’enfants handicapés (aspeh.py)
- Eligibilité à l'aide Paris Energie Familles, sans prendre en compte les conditions financières (paris_energie_familles)
- Eligibilité à l'aide Paris Forfait Familles (paris_forfait_familles)
- Éligibilité au Complément Santé Paris pour les personnes âgées (paris_complement_sante)
- aide Paris Logement pour les personnes âgées (paris_logement)
- Pass Paris Seniors (paris_pass_seniors)
- Paris Solidarité pour les personnes âgées (psol)
- Complément Santé Paris pour les personnes handicapées (paris_complement_sante)
- Pass Paris Access (paris_pass_access)
-  Paris Solidarité pour les personnes handicapées (psol)
- Paris Logement pour les personnes handicapées et les personnes agées (paris_logement)
- Paris Logement pour les couples avec enfant(s) - (paris_logement)
- ...

**Comment by jenovateurs** [comment]
La variable `parisien` est à `true`, lorsque l'utilisateur ou l'utilisatrice répond par la positive à la question dynamique : 
```
  parisien: new BooleanProperty({
        question: ({ simulation }) => {
            return `Avez-vous habité Paris au moins 3 ans depuis ${yearsAgo(5, simulation.dateDeValeur)} ?`;
        },
    }),
```
Cette question s'affiche après avoir mis un code postal parisien et deux questions plus tard.

**Comment by yasmine-glitch** [comment]
Analyse des aides de la ville de Paris :

1) Allocation de soutien aux parents d’enfants handicapés (aspeh.py)
✅ l'aide existe toujours et elle est codée dans OF 
- url ville de paris : https://www.paris.fr/pages/aides-sociales-pour-les-familles-174#aides-en-soutien-a-la-parentalite
- chemin yml : data/benefits/openfisca/paris_logement_aspeh.yml
- chemin OF : openfisca_paris/familles/aspeh.py

2) Eligibilité à l'aide Paris Energie Familles, sans prendre en compte les conditions financières (paris_energie_familles)
✅ l'aide existe toujours et elle est codée dans OF 
- url ville de paris : https://www.paris.fr/pages/aides-sociales-pour-les-familles-174#comment-alleger-vos-factures-d-energie
- chemin yml : data/benefits/openfisca/paris_energie_familles.yml
- chemin OF : openfisca_paris/familles/paris_energie_familles.py

3) Eligibilité à l'aide Paris Forfait Familles (paris_forfait_familles)
✅ l'aide existe toujours et elle est codée dans OF 
- url ville de paris : https://www.paris.fr/pages/aides-sociales-pour-les-familles-174#aides-en-soutien-a-la-parentalite
- chemin yml : data/benefits/openfisca/paris_forfait_familles.yml
- chemin OF : openfisca_paris/familles/paris_forfait_familles.py

4) Éligibilité au Complément Santé Paris pour les personnes âgées (paris_complement_sante)
✅ l'aide existe toujours et elle est codée dans OF 
- url ville de paris : https://www.paris.fr/pages/aides-a-la-sante-3869
- chemin yml : data/benefits/openfisca/paris_complement_sante.yml
- chemin OF : openfisca_paris/paris_complement_sante.py

5) aide Paris Logement pour les personnes âgées (paris_logement)
✅ l'aide existe toujours et elle est codée dans OF 
- url ville de paris : qui-sont-les-beneficiaires-du-paris-logement
- chemin yml :  data/benefits/openfisca/paris_logement.yml
- chemin OF : openfisca_paris/personnes_agees/paris_logement.py

6) Pass Paris Seniors (paris_pass_seniors)
✅ l'aide existe toujours et elle est codée dans OF 
- url ville de paris : https://www.paris.fr/pages/aides-aux-transports-3848/#les-pass-paris-seniors-ou-access
- chemin yml :  data/benefits/openfisca/paris_pass_seniors.yml
- chemin OF : openfisca_paris/personnes_agees/paris_pass_seniors.py

7) Paris Solidarité pour les personnes âgées (psol)
✅ l'aide existe toujours et elle est codée dans OF 
- url ville de paris : https://www.paris.fr/pages/minimas-sociaux-garanties-de-ressources-3846#paris-solidarite-psol-pour-les-seniors
- chemin yml :  data/benefits/openfisca/paris_logement_psol.yml
- chemin OF : openfisca_paris/personnes_agees/psol.py

8) Complément Santé Paris pour les personnes handicapées (paris_complement_sante)
✅ l'aide existe toujours et elle est codée dans OF 
- url ville de paris : le-complement-sante-paris-pour-les-personnes-en-situation-de-handicap
- chemin yml :  data/benefits/openfisca/paris_complement_sante.yml
- chemin OF : openfisca_paris/personnes_handicapees/paris_complement_sante.py

9) Pass Paris Access (paris_pass_access)
✅ l'aide existe toujours et elle est codée dans OF 
- url ville de paris : https://www.paris.fr/pages/aides-aux-transports-3848/#les-pass-paris-seniors-ou-access
- chemin yml :  data/benefits/openfisca/paris_pass_access.yml
- chemin OF : openfisca_paris/personnes_handicapees/paris_pass_access.py

10) Paris Solidarité pour les personnes handicapées (psol)
✅ l'aide existe toujours et elle est codée dans OF 
- url ville de paris : https://www.paris.fr/pages/minimas-sociaux-garanties-de-ressources-3846#paris-solidarite-psol-pour-les-personnes-en-situation-de-handicap
- chemin yml :  data/benefits/openfisca/paris_logement_psol.yml
- chemin OF : openfisca_paris/personnes_handicapees/psol.py

11) Paris Logement pour les personnes handicapées et les personnes agées (paris_logement)
✅ l'aide existe toujours et elle est codée dans OF 
- url ville de paris : https://www.paris.fr/pages/aides-au-logement-3827/#qui-sont-les-beneficiaires-du-paris-logement
- chemin yml :  data/benefits/openfisca/paris_logement.yml
- chemin OF : openfisca_paris/paris_logement.py

12) Paris Logement pour les couples avec enfant(s) - (paris_logement)
✅ l'aide existe toujours et elle est codée dans OF 
- url ville de paris : https://www.paris.fr/pages/aides-au-logement-3827/#paris-logement-familles
- chemin yml :  data/benefits/openfisca/paris_logement_familles.yml
- chemin OF : openfisca_paris/paris_logement_fam.py

**Comment by jenovateurs** [comment]
Il semblerait que certaines aides n'ont pas leurs montants à jour. Voici un premier ticket sur le sujet : [4579](https://github.com/betagouv/aides-jeunes/issues/4579)
