### ISSUE TITLE
Améliorer l'enchainement des questions sur le chômage (date d'inscription à FT, date de début du chômage)

### ISSUE THREAD

**Issue by yasmine-glitch** [betagouv/aides-jeunes#4575]
![Image](https://github.com/user-attachments/assets/f5d4d9ee-eb11-4e3b-bfe9-d55ae2303fdf)

**Comment by Shamzic** [comment]
On a un meilleur taux de conversion pour les simulation terminée sur la version "reformulation" (dont le contenu est "Depuis quand êtes-vous inscris à France Travail?") sur le mois d'août : 



![Image](https://github.com/user-attachments/assets/9da45f0b-d123-47db-aea9-8c8205e7cbb4)
