### ISSUE TITLE
Retravailler la question de l'inaptitude

### ISSUE THREAD

**Issue by yasmine-glitch** [betagouv/aides-jeunes#4655]
- [x] Ajouter un point d'information définition de l'inaptitude au travail
- [ ] Ordre des questions entre handicap et inaptitude

Peu signifier différentes choses : 

> Une personne qui a l’AH peut travailler / elle va pouvoir pourvoir faire un temps partiel ou quelques heures par exemple.
Si son état de santé se détériore, s'arrêter un temps, ...
Peut-être préciser inapte (AH, ... ) ou inaptitude temporaire autre solution intervertir les questions.

**Comment by Shamzic** [comment]
Le sujet du 2e point sera traité ici : https://github.com/orgs/betagouv/projects/42/views/1?pane=issue&itemId=84198492&issue=betagouv%7Caides-jeunes%7C4668
