### ISSUE TITLE
Investiguer sur ces deux aides Frequencio et garantie pret etudiant eligibilite

### ISSUE THREAD

**Issue by jenovateurs** [betagouv/aides-jeunes#4664]
[frequencio-jeunes](https://mes-aides.1jeune1solution.beta.gouv.fr/aides/region-occitanie-frequencio-jeunes) (non concernée, j'habite dans la même ville que ma fac) /Précision à indiquer lors de la saisie de la ville ?
[eligibilite](https://mes-aides.1jeune1solution.beta.gouv.fr/aides/garantie_pret_etudiant_eligibilite) (je suis incapable de rembourser des mensualités, je n'ai pas de revenus) / A conditionner s'il y a des revenus ?

**Comment by yasmine-glitch** [comment]
- [ ] Prêt étudiant garanti par l'Etat : pas besoin d'avoir des revenus pour demander ce prêt, puisque le remboursement peut être différé. L'étudiant commence à rembourser une fois qu'il a trouvé un travail. J'ai ouvert [une PR](https://github.com/betagouv/aides-jeunes/pull/4675) pour préciser la description de l'aide.

- [ ] Fréquencio jeunes :  cette aide est destinée aux personnes qui ont moins de 18 ans. Correction faite [dans cette PR ](https://github.com/betagouv/aides-jeunes/pull/4677). Il y a une autre aide très similaire pour les moins de 26 ans [(à ajouter)](https://github.com/betagouv/aides-jeunes/issues/4678). La personne dit (non concernée, j'habite dans la même ville que ma fac). Elle est éligible à cette aide mais pas intéressée. Je ne vois pas d'amélioration de modélisation pour cette aide.
