### ISSUE TITLE
Correctif des labels de la modale de récapitulatif par email/sms

### ISSUE THREAD

**Issue by Shamzic** [betagouv/aides-jeunes#4691]
Vérifier et corriger les incohérences de label entre le bouton et le contenu de la modale 
+
Ça aurait été cool de trouver un moyen de centraliser la chaîne "Je reçois mon récapitulatif et je me fais accompagner par téléphone" qui est présente plusieurs fois.

**Comment by jenovateurs** [comment]
Problème résolu avec l'arrêt de l'ab testing.
