### ISSUE TITLE
Investiguation données simulation avec la ville de Saint-Louis (La Réunion)

### ISSUE THREAD

**Issue by Shamzic** [betagouv/aides-jeunes#4746]

**Comment by jenovateurs** [comment]
Tests complémentaires de ma part en discutant avec Yasmine aujourd'hui.
Le système ne marche pas ou plus de leur côté. On obtient le résultat suivant : ![Image](https://github.com/user-attachments/assets/ee18eb57-0fbb-4ab4-aaaa-bd7b0cdc30d1)
Ce qui n'est ni pro ni rassurant pour l'utilisateur, l'environnement laravel est paramétré en mode développeur et non en mode production. Car on aurait pas la trace d'erreur.
Je suis partant pour passer en privée l'aide et couper le système de récupération de données. En vue d'une réparation et (mise au norme de sécurité de leur côté) et validation RGPD du notre. 
Les statistiques de demande ne sont pas top : 
![Image](https://github.com/user-attachments/assets/2af0216a-16a0-4108-91b0-0b2f51f605b8)
Et le nombre de clic sur le téléservice est haut mais non fonctionnel.
![Image](https://github.com/user-attachments/assets/bb7791e3-9de8-4030-8d29-f90df3d4950f)

**Comment by jenovateurs** [comment]
Décision de mettre en pause pour le moment.

**Comment by jenovateurs** [comment]
Décision de mettre en pause pour le moment.
