### ISSUE TITLE
Corriger l'attribution du RSA

### ISSUE THREAD

**Issue by MattiSG** [betagouv/aides-jeunes#490]
Clarifier la responsabilité de la Caf sur le sujet, et a minima mentionner les départements comme attributeurs.

- http://www.caissedesdepotsdesterritoires.fr/cs/ContentServer?pagename=Territoires/Articles/Articles&cid=1250278747925
- http://alpesdusud.alpes1.com/news/locales/57965/alpes-du-sud-un-simulateur-pour-evaluer-vos-droits-aux-aides-sociales-en-moins-de-7-minutes

**Comment by monbocal** [comment]
La modification du descriptif, dans le cadre de la refonte de droits.js , pourrait-elle répondre à cette demande ?

**Comment by MattiSG** [comment]
Comme premier quick fix, oui, d'où « a minima mentionner les départements comme attributeurs ». Mais je pense que le souci est lié à l'appartenance à la catégorie Caf, avec le logo associé.
