### ISSUE TITLE
Déclarer l'hébergement d'adultes dans son foyer

### ISSUE THREAD

**Issue by monbocal** [betagouv/aides-jeunes#492]
En tant que bénéficiaire potentiel,
Je souhaite déclarer l'ensemble des personnes vivant dans mon foyer et non uniquement mes enfants à charge,
Afin de pouvoir avoir une meilleure estimation de mes aides

--

Mail du 09/03/17 19:08
Quand on héberge à titre gratuit quelqu'un chez soi, ses revenus entrent en compte pour le calcul d'aides, notamment pour l'APL

**Comment by guillett** [comment]
Mail du 9 mars 2018 à 07:27
