### ISSUE TITLE
Déclarer des nombres avec des virgules sur la page des ressources

### ISSUE THREAD

**Issue by monbocal** [betagouv/aides-jeunes#523]
En tant que bénéficiaire potentiel d'une aide,
Je souhaite pouvoir entrer des montants à virgule avec des points sur tous les navigateurs,
Afin de ne pas voir le message "Montants invalides".

Ce problème a été testé sous Firefox 52.0.1 mais n'a pas réussi à être reproduit sous Chrome 57.0.2987.110 .

--
Mail du 15/03/17 20:50 et suivants dans la discussion

**Comment by guillett** [comment]
>Dommage toujours retour montant invalide lorsque j'utilise le point du clavier numérique ou celui du clavier alpha il faut absolument la virgule sous Firefox
 Par contre avec Internet explorer cela fonctionne.

**Comment by guillett** [comment]
Firefox semble comprendre le . comme le séparateur des milliers. Affaire à suivre.

**Comment by MattiSG** [comment]
> Firefox semble comprendre le . comme le séparateur des milliers.

Oui, il faut préciser l'attribut `lang` dans les `input` pour que Firefox s'ajuste. Il ne répercute pas le `lang` des parents.
