### ISSUE TITLE
Sauvegarder sa progression

### ISSUE THREAD

**Issue by moimael** [betagouv/aides-jeunes#54]
Bonjour,

Le questionnaire d'aide est relativement long, il serait pratique de pouvoir reprendre le questionnaire la ou on le laisse pour continuer plus tard. 

Après avoir remplit la moitié du questionnaire je me suis rendu compte que je n'avais pas certains papiers sous la main et que je devais tout refaire, c'est pas terrible comme experience utilisateur.

Un système à base de localstorage serait suffisant dans un premier temps, le top serais de pouvoir avoir un compte que l'ont puisse metre à jour d'année en année.

Merci et super boulot !

**Comment by MattiSG** [comment]
Bonjour @moimael et merci beaucoup pour ces retours !

Nous gérons normalement déjà la [restauration par `sessionStorage`](https://github.com/sgmap/mes-aides-ui/blob/57a549b3c62fc050b75614e5ed1cb3dce5bb2c40/app/js/services/situationService.js#L64-L78). Si elle n'a pas fonctionné chez toi, pourrais-tu nous donner ton OS et navigateur afin que nous tentions de reproduire le problème ?  :)

La gestion des comptes est une problématique à part entière qui a des enjeux autres que purement techniques (politique d'une part : CNIL & administrations partenaires, usage d'autre part : quels services associer à un compte ?).
J'envisage aujourd'hui plus facilement une URL « privée » avec un hash qui te permettrait de restaurer ta session plus qu'un compte. Qu'en penses-tu ? Un tel système aurait-il répondu à ton besoin ?

Bon dimanche,
Matti

**Comment by moimael** [comment]
Bonjour !

Effectivement j'ai bien une entrée sessionStorage dans mon navigateur mais elle semble vide.
En tout cas la restauration de session ne fonctionne pas.
J'utilise Firefox 37.0.2 sur une Fedora 22.

![session_mes_aides](https://cloud.githubusercontent.com/assets/1479859/7338523/92989438-ec4e-11e4-8c45-1fe38c45d454.png)

Oui une simple url privée pourrais faire l'affaire :) Sinon le top serait une intégration avec le compte unifié mon-service-public (même si je me doute que ça doit être relativement complexe à mettre en oeuvre)

Bon dimanche également !

**Comment by MattiSG** [comment]
Ok, il s'agit effectivement de la valeur par défaut. Je crée une issue en bug de `sessionStorage`, et je laisse cette issue ouverte pour discuter des modalités de sauvegarde de progression tant qu'une implémentation spécifique n'est pas lancée  :)

**Comment by MattiSG** [comment]
Comme vu dans #58 : la restauration fonctionne techniquement, mais est réinitialisée au démarrage d'une simulation, ce qui en fait perdre l'usage principal. Il faut réfléchir l'interface pour permettre à la fois le nettoyage d'une simulation existante, et la récupération d'une en cours.

**Comment by moimael** [comment]
Je ne sais pas si vous utilisez/comptez utiliser une archi Flux (avec altjs par exemple) mais une des fonctions vraiment intéressante est le snapshot de l'état de l'app à n'importe quel moment ainsi que sa restauration.

Pour la reprise d'une simulation c'est juste parfait :)

http://alt.js.org/docs/takeSnapshot/

**Comment by MattiSG** [comment]
Merci @moimael pour la référence ! Je vais regarder ça par curiosité, mais on est sur un changement architectural majeur, non ?

**Comment by moimael** [comment]
Je n'ai pas spécialement jeté un œil au code, juste vu que c’était de l'angular. Effectivement si c'est du angular/mvc classique c'est un changement majeur. 

L’équivalent en MVC serait un poil plus dur a faire étant donné que l'état de l'application n'est pas centralisé au même endroit contrairement a une archi de type flux. Après peux être que des libs angular existent pour sérialiser l'état de l'app.

**Comment by MattiSG** [comment]
+1 mail du 6 déc. 2015 à 17:02

**Comment by MattiSG** [comment]
Retour AMA lié au mécanisme de chargement :

> J'ai quitté la page internet pour me rentre sur mon application iBooks. 
> 
> En revenant sur internet, la page s'est rechargé à la page que j'avais quitté, mais impossible de cliquer sur valider pour continuer. 
> 
> Du coup, j'ai fait un retour en arrière [et le message "une erreur est survenue" est apparu].

**Comment by MattiSG** [comment]
+1 mail du 27/06/2016 à 00:18

**Comment by guillett** [comment]
Bonjour @MattiSG, je suis en train de regarder la liste des tickets ouverts pour essayer de résoudre les plus 'faciles' pour me faire la main sur l'application.

J'ai réussi à répliquer ce problème, qui vient du fait qu'en cliquant sur "Commencer la simulation" on réinitialise le SessionStorage (alors que si on va directement dans une page, les données sont conservées et affichées).

Y-a-t-il eu une discussion sur le comportement/UI souhaité:
- Bouton supplémentaire dans la page d'accueil lorsque une simulation est déjà présente dans le sessions store ? Peut-être un filtre sur la dateDeValue serait pertinent si la simulation est vraiment ancienne ?
- Je pense qu'il est judicieux de 'simplement' reprendre le formulaire depuis le début avant les différents champs pré-remplis. Mais y-a-t-il un compromis de ce côté là ?

- La date de valeur devrait peut-être apparaitre dans le récapitulatif de la simulation [à droite] (peut-être seulement si la simulation est "ancienne")

**Comment by MattiSG** [comment]
Bonjour @guillett, bienvenue, et merci beaucoup de ta proposition d'avancer sur ce sujet ! Ce serait sans aucun doute un excellent ajout à Mes Aides  :)

> Bouton supplémentaire dans la page d'accueil lorsque une simulation est déjà présente dans le sessions store ?

Oui, ça me semble être une bonne idée : on ajoute un bouton « Reprendre la simulation » en CTA principal (vert) à côté de « Commencer la simulation », renommé en « Commencer une nouvelle simulation » en CTA secondaire (bleu).

> Mais y-a-t-il un compromis de ce côté là ?

Il pourrait être pertinent de reprendre à la dernière étape non remplie si la situation est incomplète, mais ça me semble un peu plus de logique que nécessaire. Commençons déjà par reprendre au début !  :)

Pour ce qui est des dates de valeur, de leur affichage et d'une logique à effectuer dessus, je ne pense pas qu'il faille trop se soucier de l'invalidation. On parle bien de `sessionStorage` et non de `localStorage` pour le moment, donc tout s'efface si l'onglet est fermé ou que le navigateur est quitté. C'est probablement suffisant pour ne pas reprendre des simulations périmées !
L'utilisation de `localStorage` pourrait être pertinente pour permettre une reprise dans un contexte différent, mais pose beaucoup de difficultés spécifiques (invalidation du cache comme tu l'as envisagé, mais aussi remise en question de la capacité à construire deux simulations en parallèle dans le même navigateur).

À ta disposition pour avancer sur ce sujet !  :)
