### ISSUE TITLE
Exécuter les tests d'intégration sur plusieurs navigateurs

### ISSUE THREAD

**Issue by guillett** [betagouv/aides-jeunes#566]
Cf. https://github.com/sgmap/mes-aides-ui/pull/557#pullrequestreview-40707770

**Comment by MattiSG** [comment]
@guillett Merci de détailler les issues pour éviter que comprendre leur enjeu soit un jeu de labyrinthe, d'autant plus que les références peuvent être éditées. Ne pas hésiter à copier-coller sous la forme d'une citation en faisant une référence vers la source originale.
