### ISSUE TITLE
Améliorer la déclaration de revenus de l'année passée

### ISSUE THREAD

**Issue by monbocal** [betagouv/aides-jeunes#639]
La déclaration de revenus de l'année passée (les revenus de n-2) pourrait être améliorée.

Sur une déclaration de revenus conjointe, les revenus des deux personnes sont côtes à côtes et non l'une après l'autre.

Cela permettrait de pouvoir plus facilement remplir ces champs.

**Comment by guillett** [comment]
OK, le texte qui est aujourd'hui à côté, le mettre en dessous.
