### ISSUE TITLE
Service Civique : comment l'intégrer ?

### ISSUE THREAD

**Issue by monbocal** [betagouv/aides-jeunes#814]
Suite à une suggestion reçue par mail - recherches supplémentaires nécessaires.

Notamment concernant l'indemnité de service civique sur https://www.service-civique.gouv.fr/faq-volontaire :

> Non, l’indemnité de Service Civique n’est pas prise en compte dans le calcul des allocations logement.

> Non, le versement du revenu de solidarité active est suspendu pendant toute la durée de la mission de Service Civique et reprend au terme de la mission.

> Oui, l’indemnité de Service Civique et l’AAH sont cumulables, l’indemnité de Service Civique n’est pas prise en compte dans le calcul de l’AAH.

> Oui, le fait d’être en Service Civique n’a pas d’impact sur l’éligibilité à une bourse étudiante, ni sur son montant. L’indemnité de Service Civique n’est pas prise en compte dans le calcul de la bourse.

Aussi sur service public : https://www.service-public.fr/particuliers/vosdroits/F13278

Au final, l'indemnité retire des choses notamment par rapport au RSA, mais son montant n'impacterait pas les autres aides ? Et au niveau des revenus n-2 ça se déclare comment ? 

Peut-être faudrait-il contacter directement le service civique pour voir avec eux comment on peut les intégrer en échange de visibilité sur leur site ?

**Comment by monbocal** [comment]
92K jeunes en 2016.
125K en 2017.

**Comment by guillett** [comment]
Email du 26/11/2018 à 21:21.
