### ISSUE TITLE
Simulation – Mode Expert

### ISSUE THREAD

**Issue by monbocal** [betagouv/aides-jeunes#847]
Le but : permettre de faire une simulation en remplissant sur une seule page toutes les données – au lieu de devoir répondre à toutes les questions une à une.
Public visé : professionnels de Mes Aides

Les étapes qui font sens :
- Dans un premier temps, à partir d’une simulation donnée, avoir accès en un clic à la requête envoyée à OpenFisca
> déjà possible en cliquant sur l'option cachée "Créer un test dans la nouvelle interface"

- Ensuite, permettre directement dans Mes Aides de modifier la requête OpenFisca ou bien d’en créer une nouvelle

- Ensuite, faciliter la modification ou la création d’une requête à l’aide de champs de formulaires ( par exemple, plutôt que de taper « menage: loyer: 328 » avec les sauts de ligne, avoir une case « Loyer » à remplir avec 328 )

- Enfin, se rapprocher des professionnels de l’aide sociale pour avoir un meilleur wording et leur permettre d’utiliser Mes Aides sans devoir suivre le cheminement utilisateur que nous proposons

Qu'en pensez-vous ?

**Comment by guillett** [comment]
Tu peux regarder ça déjà
https://betagouv.github.io/openfisca-tracer/
