### ISSUE TITLE
[AAH] Restriction substantielle et durable d'accès à l'emploi

### ISSUE THREAD

**Issue by monbocal** [betagouv/aides-jeunes#977]
Bonjour,

Dans le cas du handicap à moins de 80%, par défaut, la case "Avez-vous une restriction substantielle et durable d'accès à l'emploi reconnue par la CDAPH ?" est indiquée oui.

Je reçois de très nombreux faux positifs à cause de cela :
- personnes qui n'ont pas fait le lien avec l'AAH / pas lu
- personnes qui confondent cela avec la RQTH

Deux pistes :
- soit mettre par défaut "non"
- soit mettre aucune valeur par défaut et forcer l'utilisateur à remplir

Tout en changeant le tooltip pour mettre en avant le fait que ce n'est pas la RQTH.

**Comment by monbocal** [comment]
Origine possible de cette confusion (outre le fait que c'est abrégé en RSDAE et que ça fait un autre acronyme à retenir et qu'entre RQTH / AAH / RSDAE / CADPH on comprend que l'utilisateur se trompe), c'est que cette notion date de 2011 (décret : http://www.wk-rh.fr/actualites/upload/decret-2011-974-16-aout-2011-AAH.pdf ). Jusqu'alors, c'était une "incapacité à retrouver un travail".


J'ai aussi trouvé ce super guide https://handicap.gouv.fr/IMG/pdf/guide_pratique_aah.pdf .

**Comment by monbocal** [comment]
cc @ManonLger ! En gros, ça serait changer la valeur par défaut d'un tooltip :)

**Comment by monbocal** [comment]
Au final, on va modifier seulement le texte du tooltip.

**Comment by guillett** [comment]
Pas tout à fait, la proposition est de faire une amélioration en deux étapes.

Pour commencer on va voir ce qu'apporte l'ajout d'un message d'aide pour expliciter le fait que la restriction substantielle et durable d'accès à l'emploi (RSDAE) est différente de la reconnaissance de la qualité de travailleur handicapé (RQTH).

Si cela ne change rien, on testera les propositions complémentaires que tu as faites.

**Comment by guillett** [comment]
Pour info

```js
db.getCollection('situations').mapReduce(function() {
    emit(this.dateDeValeur.toISOString().slice(0,7) + ";" +  this.individus[0].aah_restriction_substantielle_durable_acces_emploi,1);
}, function(k,v) {
    return Array.sum(v);
}, {
    query: {
        'dateDeValeur': { $gt: ISODate('2018-07-01')},
        'individus.0.aah_restriction_substantielle_durable_acces_emploi': { $exists: true },
        modifiedFrom: { $exists: false },
    },
    out: { inline: 1 },
}).results.map(function(o) {
    return o._id + ";" + o.value;
}).join('\n')
```



Somme - Nombre | Données |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
Mois | false | true | Total Résultat |   | Taux | Taux
2018-08 | 2399 | 3700 | 6099 |   | 39,33 % | 60,67 %
2018-09 | 3277 | 5028 | 8305 |   | 39,46 % | 60,54 %
2018-10 | 3291 | 5093 | 8384 |   | 39,25 % | 60,75 %
2018-11 | 4118 | 6744 | 10862 |   | 37,91 % | 62,09 %
2018-12 | 4505 | 7830 | 12335 |   | 36,52 % | 63,48 %
2019-01 | 2194 | 3859 | 6053 |   | 36,25 % | 63,75 %
2019-02 | 1 | 1 | 2 |   |   |  
2019-03 | 1 | 1 | 2 |   |   |  
Total Résultat | 19786 | 32256 | 52042 |   |   |  


1/3 des personnes à qui on demande la RSDAE répond « Non » à la question.
